import React from "react";
import {
  Shield,
  Linkedin,
  Github,
  Twitter,
  Zap,
  Instagram,
  Mail,
  Play,
  RotateCcw,
  Wand2,
  Check,
  X,
  Database,
  Table2,
  Code2,
  Terminal,
  LineChart,
  SlidersHorizontal,
  ChevronLeft, ChevronRight
  
} from "lucide-react";

export const Icons = {
  logo: Shield,
  gitHub: Github,
  linkedin: Linkedin,
  twitter: Twitter,
  zap: Zap,
  instagram: Instagram,
  mail: Mail,
  play: Play,
  rotateCounterClockwise: RotateCcw,
  wand2: Wand2,
  check: Check,
  x: X,
  database: Database,
  table: Table2,
  code: Code2,
  terminal: Terminal,
  lineChart: LineChart,
  sliders: SlidersHorizontal,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
};
